### ISSUE TITLE
undefined function mongo:command/2

### ISSUE THREAD

**Issue by ganeshrd** [synrc/kvs#36]
Hello every one,
I have been following the readme instructions related to mongodb. The kvs module gives me this
settings:
`>kvs:config(dba).
  store_mongo`
`>kvs:version().
  {version,"KVS MONGO"}`
Then after `kvs:join().`
 I got the error message.
I don't see any 'mongo.erl' module in comtihon/mongodb-erlang sources nore in kvs's package.
Would you help me understand my wrongs?
Thanks for your time,
Best regards

**Comment by 5HT** [comment]
Mongo backend was managed once by @cystbear AFAIR

**Comment by ganeshrd** [comment]
Does it mean i need to write my own api?

**Comment by 5HT** [comment]
No as I see from module, you just need fill gaps and maybe use old library original authors used.

**Comment by ganeshrd** [comment]
Oh ok.
Thank you.

**Comment by 5HT** [comment]
Guys how do you use `store_mongo`, where Ganesh could take this `mongo` module?
Please help him!

**Comment by ganeshrd** [comment]
I have checked on @cystbear erlmongo repo. And found also this 'mongo' module call. I know that @TonyGen 's mongodb-erlang uses this module's name for its api. I could try to plug it. Is that a track?

**Comment by Spoowy** [comment]
@ganeshrd how did that go for you?

**Comment by 5HT** [comment]
These guys abandoned their shit, anyway mongo support was dropped.
